/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/wrangler.jsonc --env=production --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: 101cd1834f99352a7534e507a5ad51a6)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEPLOYMENT_ENV: "production";
	API_ORIGIN: "https://heritg-share-api-ulvjjfvqpq-et.a.run.app";
	APP_ORIGIN: "https://heritg.us";
	EDGE_CLIENT_IP_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_ENV" | "API_ORIGIN" | "APP_ORIGIN" | "EDGE_CLIENT_IP_PRIVATE_KEY">> {}
}
